// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260211083231_AddOverallKpiResult")]
    partial class AddOverallKpiResult
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.BbAnwKpi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Division")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("division");

                    b.Property<decimal?>("KpiPercent")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("kpi_percent");

                    b.Property<string>("NetworkEngineerKpi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("network_engineer_kpi");

                    b.Property<string>("Section")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("section");

                    b.HasKey("Id");

                    b.ToTable("BbAnwKpi", "dbo");
                });

            modelBuilder.Entity("backend.Models.BbAnwKpiNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BbAnwKpiId")
                        .HasColumnType("int")
                        .HasColumnName("bb_anw_kpi_id");

                    b.Property<byte>("Month")
                        .HasColumnType("tinyint")
                        .HasColumnName("month");

                    b.Property<string>("NodeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("node_code");

                    b.Property<long?>("TotalMinutes")
                        .HasColumnType("bigint")
                        .HasColumnName("total_minutes");

                    b.Property<int?>("TotalNodes")
                        .HasColumnType("int")
                        .HasColumnName("total_nodes");

                    b.Property<int?>("UnavailableMinutes")
                        .HasColumnType("int")
                        .HasColumnName("unavailable_minutes");

                    b.Property<short>("Year")
                        .HasColumnType("smallint")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("BbAnwKpiId", "NodeCode", "Month", "Year")
                        .IsUnique()
                        .HasDatabaseName("UQ_BbAnwKpiNode_Row");

                    b.ToTable("BbAnwKpiNode", "dbo");
                });

            modelBuilder.Entity("backend.Models.EmailRecipient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("email");

                    b.Property<byte>("V")
                        .HasColumnType("tinyint")
                        .HasColumnName("v");

                    b.HasKey("Id");

                    b.ToTable("EmailRecipients", "dbo");
                });

            modelBuilder.Entity("backend.Models.IpNwOpKpi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Division")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("division");

                    b.Property<double?>("KpiPercent")
                        .HasColumnType("float")
                        .HasColumnName("kpi_percent");

                    b.Property<string>("NetworkEngineerKpi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("network_engineer_kpi");

                    b.Property<string>("Section")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("section");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("IpNwOpKpi", "dbo");
                });

            modelBuilder.Entity("backend.Models.IpNwOpKpiMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AreaCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("area_code");

                    b.Property<int>("IpNwOpKpiId")
                        .HasColumnType("int")
                        .HasColumnName("ip_nw_op_kpi_id");

                    b.Property<byte>("Month")
                        .HasColumnType("tinyint")
                        .HasColumnName("month");

                    b.Property<int?>("TotalMinutes")
                        .HasColumnType("int")
                        .HasColumnName("total_minutes");

                    b.Property<int?>("TotalNodes")
                        .HasColumnType("int")
                        .HasColumnName("total_nodes");

                    b.Property<int?>("UnavailableMinutes")
                        .HasColumnType("int")
                        .HasColumnName("unavailable_minutes");

                    b.Property<short>("Year")
                        .HasColumnType("smallint")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("IpNwOpKpiId", "AreaCode", "Month", "Year")
                        .IsUnique()
                        .HasDatabaseName("UQ_IpNwOpKpiMetrics");

                    b.ToTable("IpNwOpKpiMetrics", "dbo");
                });

            modelBuilder.Entity("backend.Models.KpiDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("createdAt");

                    b.Property<string>("DescriptionOfKPI")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("descriptionOfKPI");

                    b.Property<string>("KeyPerformanceIndicators")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("keyPerformanceIndicators");

                    b.Property<byte>("Month")
                        .HasColumnType("tinyint")
                        .HasColumnName("month");

                    b.Property<string>("Perspectives")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("perspectives");

                    b.Property<int>("PointsApplicable")
                        .HasColumnType("int")
                        .HasColumnName("pointsApplicable");

                    b.Property<string>("StrategicObjectives")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("strategicObjectives");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("unit");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("updatedAt");

                    b.Property<decimal>("Weightage")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("weightage");

                    b.Property<short>("Year")
                        .HasColumnType("smallint")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.ToTable("finaldatatables", "dbo");
                });

            modelBuilder.Entity("backend.Models.MtncRoutine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Calculation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("calculation");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("createdAt");

                    b.Property<string>("DataSources")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("dataSources");

                    b.Property<string>("DefinedOLADetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("definedOLADetails");

                    b.Property<string>("Kpi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kpi");

                    b.Property<byte>("No")
                        .HasColumnType("tinyint")
                        .HasColumnName("no");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("platform");

                    b.Property<string>("ResponsibleDGM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("responsibleDGM");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("target");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updatedAt");

                    b.Property<byte>("V")
                        .HasColumnType("tinyint")
                        .HasColumnName("v");

                    b.HasKey("Id");

                    b.ToTable("mtncroutinetable1", "dbo");
                });

            modelBuilder.Entity("backend.Models.OtnOp1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Division")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Division");

                    b.Property<decimal?>("KpiPercent")
                        .HasColumnType("decimal(6,3)")
                        .HasColumnName("KpiPercent");

                    b.Property<string>("NetworkEngineerKpi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("NetworkEngineerKpi");

                    b.Property<string>("Section")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Section");

                    b.HasKey("Id");

                    b.ToTable("OtnOp1", "dbo");
                });

            modelBuilder.Entity("backend.Models.OtnOp1Metrics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("Month")
                        .HasColumnType("tinyint")
                        .HasColumnName("Month");

                    b.Property<int>("OtnOp1Id")
                        .HasColumnType("int")
                        .HasColumnName("OtnOp1Id");

                    b.Property<string>("Site")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Site");

                    b.Property<int>("TotalMinutes")
                        .HasColumnType("int")
                        .HasColumnName("TotalMinutes");

                    b.Property<int>("TotalNodes")
                        .HasColumnType("int")
                        .HasColumnName("TotalNodes");

                    b.Property<int>("UnavailableMinutes")
                        .HasColumnType("int")
                        .HasColumnName("UnavailableMinutes");

                    b.Property<short>("Year")
                        .HasColumnType("smallint")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.HasIndex("OtnOp1Id", "Site", "Year", "Month")
                        .IsUnique()
                        .HasDatabaseName("UQ_Otn1M");

                    b.ToTable("OtnOp1Metrics", "dbo");
                });

            modelBuilder.Entity("backend.Models.OtnOp2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Division")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Division");

                    b.Property<decimal?>("KpiPercent")
                        .HasColumnType("decimal(6,3)")
                        .HasColumnName("KpiPercent");

                    b.Property<string>("NetworkEngineerKpi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("NetworkEngineerKpi");

                    b.Property<string>("Section")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Section");

                    b.HasKey("Id");

                    b.ToTable("OtnOp2", "dbo");
                });

            modelBuilder.Entity("backend.Models.OtnOp2Metrics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LinksSlaNotViolated")
                        .HasColumnType("int")
                        .HasColumnName("LinksSlaNotViolated");

                    b.Property<byte>("Month")
                        .HasColumnType("tinyint")
                        .HasColumnName("Month");

                    b.Property<int>("OtnOp2Id")
                        .HasColumnType("int")
                        .HasColumnName("OtnOp2Id");

                    b.Property<string>("Site")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Site");

                    b.Property<int>("TotalFailedLinks")
                        .HasColumnType("int")
                        .HasColumnName("TotalFailedLinks");

                    b.Property<short>("Year")
                        .HasColumnType("smallint")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.HasIndex("OtnOp2Id", "Site", "Year", "Month")
                        .IsUnique()
                        .HasDatabaseName("UQ_Otn2M");

                    b.ToTable("OtnOp2Metrics", "dbo");
                });

            modelBuilder.Entity("backend.Models.OverallKpiResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Achieved")
                        .HasColumnType("decimal(18,5)")
                        .HasColumnName("achieved");

                    b.Property<string>("AreaCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("area_code");

                    b.Property<string>("KpiCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("kpi_code");

                    b.Property<byte>("Month")
                        .HasColumnType("tinyint")
                        .HasColumnName("month");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("platform");

                    b.Property<decimal>("PointsAchieved")
                        .HasColumnType("decimal(18,5)")
                        .HasColumnName("points_achieved");

                    b.Property<int>("PointsApplicable")
                        .HasColumnType("int")
                        .HasColumnName("points_applicable");

                    b.Property<decimal>("Target")
                        .HasColumnType("decimal(18,5)")
                        .HasColumnName("target");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<short>("Year")
                        .HasColumnType("smallint")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("KpiCode", "AreaCode", "Year", "Month")
                        .IsUnique()
                        .HasDatabaseName("UQ_OverallKpiResult_Key");

                    b.ToTable("OverallKpiResult", "dbo");
                });

            modelBuilder.Entity("backend.Models.RegionData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LeaCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lea_code");

                    b.Property<string>("NetworkEngineer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("network_engineer");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("province");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("region");

                    b.HasKey("Id");

                    b.ToTable("regiondata");
                });

            modelBuilder.Entity("backend.Models.RtomArea", b =>
                {
                    b.Property<string>("AreaCode")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("area_code");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("display_name");

                    b.HasKey("AreaCode");

                    b.ToTable("rtom_area_lookup");
                });

            modelBuilder.Entity("backend.Models.ServiceFulfilmentKpi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Calculation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("calculation");

                    b.Property<string>("DataSources")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("datasources");

                    b.Property<string>("DefineDoladetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("definedoladetails");

                    b.Property<string>("Kpi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kpi");

                    b.Property<byte>("Month")
                        .HasColumnType("tinyint")
                        .HasColumnName("month");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("platform");

                    b.Property<string>("ResponsibleDgm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("responsibledgm");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("target");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updatedAt");

                    b.Property<int>("Weightage")
                        .HasColumnType("int")
                        .HasColumnName("weightage");

                    b.Property<short>("Year")
                        .HasColumnType("smallint")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.ToTable("ServiceFulfilmentKpi", "dbo");
                });

            modelBuilder.Entity("backend.Models.ServiceFulfilmentKpiMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AreaCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("area_code");

                    b.Property<decimal?>("KpiValue")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("kpi_value");

                    b.Property<byte>("Month")
                        .HasColumnType("tinyint")
                        .HasColumnName("month");

                    b.Property<int>("ServiceFulfilmentKpiId")
                        .HasColumnType("int")
                        .HasColumnName("ServiceFulfilmentKpiId");

                    b.Property<short>("Year")
                        .HasColumnType("smallint")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("ServiceFulfilmentKpiId", "AreaCode", "Month", "Year")
                        .IsUnique()
                        .HasDatabaseName("UQ_ServiceFulfilmentKpiMetrics_Row");

                    b.ToTable("ServiceFulfilmentKpiMetrics", "dbo");
                });

            modelBuilder.Entity("backend.Models.TmActivity1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Calculation")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("calculation");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("createdAt");

                    b.Property<string>("DataSources")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("dataSources");

                    b.Property<string>("DefinedOLADetails")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("definedOLADetails");

                    b.Property<string>("Kpi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kpi");

                    b.Property<byte?>("No")
                        .HasColumnType("tinyint")
                        .HasColumnName("no");

                    b.Property<string>("Platform")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("platform");

                    b.Property<string>("ResponsibleDGM")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("responsibleDGM");

                    b.Property<string>("Target")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("target");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updatedAt");

                    b.Property<byte?>("V")
                        .HasColumnType("tinyint")
                        .HasColumnName("v");

                    b.HasKey("Id");

                    b.ToTable("tmtable1", "dbo");
                });

            modelBuilder.Entity("backend.Models.TowerKpi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedAt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("createdAt");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("frequency");

                    b.Property<string>("Kpi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("kpi");

                    b.Property<byte?>("Month")
                        .HasColumnType("tinyint")
                        .HasColumnName("month");

                    b.Property<byte>("No")
                        .HasColumnType("tinyint")
                        .HasColumnName("no");

                    b.Property<string>("Responsibility")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("responsibility");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("updatedAt");

                    b.Property<byte>("V")
                        .HasColumnType("tinyint")
                        .HasColumnName("v");

                    b.Property<string>("Weightage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("weightage");

                    b.Property<short?>("Year")
                        .HasColumnType("smallint")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.ToTable("kpitowertable", "dbo");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("createdAt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("isActive")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pages_0")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pages_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pages_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pages_3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pages_4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pages_5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pages_6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pages_7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pages_8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("updatedAt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("username")
                        .HasColumnType("smallint");

                    b.Property<bool?>("v")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("backend.Models.BbAnwKpiNode", b =>
                {
                    b.HasOne("backend.Models.BbAnwKpi", "Kpi")
                        .WithMany("Nodes")
                        .HasForeignKey("BbAnwKpiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kpi");
                });

            modelBuilder.Entity("backend.Models.IpNwOpKpiMetric", b =>
                {
                    b.HasOne("backend.Models.IpNwOpKpi", "IpNwOpKpi")
                        .WithMany("Metrics")
                        .HasForeignKey("IpNwOpKpiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_IpNwOpKpiMetrics_IpNwOpKpi");

                    b.Navigation("IpNwOpKpi");
                });

            modelBuilder.Entity("backend.Models.OtnOp1Metrics", b =>
                {
                    b.HasOne("backend.Models.OtnOp1", "OtnOp1")
                        .WithMany("Metrics")
                        .HasForeignKey("OtnOp1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Otn1M_Otn1");

                    b.Navigation("OtnOp1");
                });

            modelBuilder.Entity("backend.Models.OtnOp2Metrics", b =>
                {
                    b.HasOne("backend.Models.OtnOp2", "OtnOp2")
                        .WithMany("Metrics")
                        .HasForeignKey("OtnOp2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Otn2M_Otn2");

                    b.Navigation("OtnOp2");
                });

            modelBuilder.Entity("backend.Models.ServiceFulfilmentKpiMetric", b =>
                {
                    b.HasOne("backend.Models.ServiceFulfilmentKpi", "ServiceFulfilmentKpi")
                        .WithMany("Metrics")
                        .HasForeignKey("ServiceFulfilmentKpiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ServiceFulfilmentKpiMetrics_ServiceFulfilmentKpi");

                    b.Navigation("ServiceFulfilmentKpi");
                });

            modelBuilder.Entity("backend.Models.BbAnwKpi", b =>
                {
                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("backend.Models.IpNwOpKpi", b =>
                {
                    b.Navigation("Metrics");
                });

            modelBuilder.Entity("backend.Models.OtnOp1", b =>
                {
                    b.Navigation("Metrics");
                });

            modelBuilder.Entity("backend.Models.OtnOp2", b =>
                {
                    b.Navigation("Metrics");
                });

            modelBuilder.Entity("backend.Models.ServiceFulfilmentKpi", b =>
                {
                    b.Navigation("Metrics");
                });
#pragma warning restore 612, 618
        }
    }
}
